name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 3.107.205.4
            username: ubuntu
            password: ${{ secrets.ubuntu_aws }}
            port: 22
            script: whoami

      